criaCartao('Função afim', 'O que é a fórmula da função afim', 'f(x) = ax + b')
criaCartao('Função afim', 'Como é seu gráfico?', 'Uma reta')
criaCartao('Função afim', 'Pra que serve o coeficiente a?', ' O coeficiente a é a inclinação da reta.')
criaCartao('Função afim', 'Pra que serve o coeficiente b?' ,'indica o ponto de interseção da reta com o eixo y, ou seja, onde a reta cruza o eixo vertical')
criaCartao('Função quadrática', 'Qual é a fórmula da função quadrática?', 'f(x) = ax² + bx + c')
criaCartao('Função quadrática', 'Como é seu gráfico?', 'Uma parábola')
criaCartao('Função quadrática', 'Pra que serve o coeficiente a?', 'Orienta a concavidade da parábola')
criaCartao('Função quadrática', 'Pra que serve o coeficiente b?', 'descreve como o deslocamento "lateral" e acompanha o termo x')
criaCartao('Função quadrática', 'Pra que serve o coeficiente c?', 'Valor em que a curva intersecta o eixo y')
criaCartao('Função quadrática', 'Qual a fórmula de Delta?', 'b² - 4ac')
criaCartao('Função quadrática', 'Como calcular as duas raízes?', 'x = (-b +/- √Δ')
criaCartao('Função quadrática', 'Qual a definição de máximo e sua fórmula?', 'Valor em que a curva intersecta o eixo y')
criaCartao('Função quadrática', 'Qual a definição de mínimo e sua fórmula?', 'Valor em que a curva intersecta o eixo y')
criaCartao('Razão', 'O que é razão?', 'Comparação entre duas grandezas',)
criaCartao('Proporção', 'O que é proporção?', 'Igualdade entre duas razões')
criaCartao('Regra de 3', 'O que é regra de 3?', 'Relação proporcional para encontrar uma incógnita')
criaCartao('Porcentagem', 'Qual a fórmula da porcentagem?', '(percentual/100) * valor total')
criaCartao('Média, moda e mediana', 'Qual a fórmula da média aritmética?', 'Soma dos valores/nº de valores')
criaCartao('Média, moda e mediana', 'O que é moda?', 'Valor central em um conjunto ordenado')
criaCartao('Média, moda e mediana', 'O que é mediana?', 'Valor mais frequente')
criaCartao('Probabilidade', 'Como é calculada a probabilidade?', 'nº de eventos favoráveis/nº de eventos totais')
criaCartao('Probabilidade', 'O que é um evento complementar?', 'Eventos que somados têm probabilidade igual a 1')
criaCartao('Áreas', 'Como calcula a área do triângulo?', '(b * h)/2')
criaCartao('Áreas', 'Como calcula a área de um triângulo equilátero?', '(l² * √3)/4')
criaCartao('Áreas', 'Como calcula a área do quadrado?', 'l²')
criaCartao('Áreas', 'Como calcula a área do retângulo?', 'l * h')
criaCartao('Áreas', 'Como calcula a área do circulo?', 'π * r² ')
criaCartao('Áreas', 'Como calcula a área do cone?', 'π * r (r + g)')
criaCartao('Volumes', 'Qual a fórmula do volume do cubo?', 'a³ (aresta ao cubo)')
criaCartao('Volumes', 'Qual a fórmula do volume do cilindro?', 'π * r² * h (área da base vezes a altura)')
criaCartao('Volumes', 'Qual a fórmula do volume da esfera?', '4/3 * π * r³')
criaCartao('Volumes', 'Qual a fórmula do volume do cone?', '(1/3) * π * r² * h')
criaCartao('Trigonometria', 'O que é seno?', 'Razão entre o cateto oposto e a hipotenusa')
criaCartao('Trigonometria', 'O que é cosseno?', 'Razão entre o cateto adjacente e a hipotenusa')
criaCartao('Trigonometria', 'O que é tangente?', 'Razão entre o cateto oposto e o cateto adjacente')
criaCartao('Matrizes', 'O que é matriz?', 'Tabela retangular de números organizada em linhas e colunas')
criaCartao('Matrizes', 'Como calcular o determinante de uma matriz 2x2?', 'Det = (a*d) - (b*c), onde a, b, c, d são os elementos da matriz')
criaCartao('Sistemas Lineares', 'O que é um sistema linear?', 'Conjunto de equações lineares resolvido simultaneamente')
criaCartao('Sistemas Lineares', 'Como resolver sistemas pelo método da substituição?', 'Isola uma variável em uma equação e substitui na outra')
criaCartao('Sistemas Lineares', 'Como resolver sistemas pelo método da adição?', 'Elimina uma variável somando ou subtraindo as equações')
criaCartao('P.A.', 'Qual a fórmula do termo geral da P.A.?', 'an = a1 + (n - 1) * r')
criaCartao('P.A.', 'Como calcular a soma dos n primeiros termos da P.A.?', 'Sn = (n/2) * (a1 + an)')
criaCartao('P.G.', 'Qual a fórmula do termo geral da P.G.?', 'an = a1 * q^(n-1)')
criaCartao('P.G.', 'Como calcular a soma dos n primeiros termos da P.G.?', 'Sn = a1 * (q^n - 1)/(q - 1), q ≠ 1')
criaCartao('Desvio Padrão', 'O que é desvio padrão?', 'Medida da dispersão dos dados em relação à média')
criaCartao('Logaritmos', 'Qual é a definição de logaritmo?', 'logₐ(b) é o número x tal que aˣ = b')
criaCartao('Logaritmos', 'Qual é a propriedade do produto?', 'logₐ(b*c) = logₐ(b) + logₐ(c)')
criaCartao('Logaritmos', 'Qual é a propriedade do quociente?', 'logₐ(b/c) = logₐ(b) - logₐ(c)')
criaCartao('Logaritmos', 'Qual é a propriedade da potência?', 'logₐ(bⁿ) = n * logₐ(b)')
criaCartao('Análise Combinatória', 'O que é fatorial?', 'n! = n * (n - 1) * ... * 1')
criaCartao('Análise Combinatória', 'Como calcular permutações de n elementos?', 'P(n) = n!')
criaCartao('Análise Combinatória', 'Como calcular combinações?', 'C(n, k) = n! / [k! * (n - k)!]')
criaCartao('Matrizes', 'O que é matriz?', 'Tabela retangular de números organizada em linhas e colunas')
criaCartao('Matrizes', 'Como calcular o determinante de uma matriz 2x2?', 'Det = (a*d) - (b*c), onde a, b, c, d são os elementos da matriz')
